// <auto-generated />
using Maqta.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maqta.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220618210409_seedProducts")]
    partial class seedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maqta.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "good car for you",
                            Name = "Car",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "good bus for you",
                            Name = "Bus",
                            Price = 18.5
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "good bike for you",
                            Name = "Bike",
                            Price = 3.5
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "good pen for you",
                            Name = "Pen",
                            Price = 1.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
